services:
  cassandra-asia:
    image: cassandra:4.1
    container_name: cassandra-asia
    restart: unless-stopped
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=Asia
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_SEEDS=cassandra-asia,cassandra-europe,cassandra-america
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9042:9042"
    volumes:
      - cassandra-asia-data:/var/lib/cassandra
    networks:
      - cassandra-net

  cassandra-europe:
    image: cassandra:4.1
    container_name: cassandra-europe
    restart: unless-stopped
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=Europe
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_SEEDS=cassandra-asia,cassandra-europe,cassandra-america
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9043:9042"
    volumes:
      - cassandra-europe-data:/var/lib/cassandra
    networks:
      - cassandra-net

  cassandra-america:
    image: cassandra:4.1
    container_name: cassandra-america
    restart: unless-stopped
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=America
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_SEEDS=cassandra-asia,cassandra-europe,cassandra-america
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9044:9042"
    volumes:
      - cassandra-america-data:/var/lib/cassandra
    networks:
      - cassandra-net

  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Basic settings
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listener configs
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      
      # Storage and performance settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
      
      # Topic settings
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - cassandra-net

volumes:
  cassandra-asia-data:
  cassandra-europe-data:
  cassandra-america-data:
  kafka-data:

networks:
  cassandra-net:
    driver: bridge