services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    restart: unless-stopped
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9042:9042" 
      - "7000:7000" 
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - cassandra-net

volumes:
  cassandra-data:

networks:
  cassandra-net:
    driver: bridge
